const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const {transformSync}=require('next/dist/build/swc');
function load(file,mocks){const code=transformSync(fs.readFileSync(file,'utf8'),{filename:file,jsc:{parser:{syntax:'ecmascript'},target:'es2020'},module:{type:'commonjs'}}).code;const module={exports:{}};vm.runInNewContext(code,{module,exports:module.exports,require:k=>k in mocks?mocks[k]:require(k),process,console,Date});return module.exports.default;}
function response(){return{code:200,body:null,setHeader(){},status(code){this.code=code;return this;},json(body){this.body=body;return this;}};}
const confirmed={id:'user-1',email:'private@example.com',email_confirmed_at:'2026-10-07T15:00:00Z',user_metadata:{signup_tracking_version:2,signup_attribution:{utm_source:'x',utm_campaign:'sports',first_url:'https://www.sharps-signal.com/?utm_source=x&email=private@example.com'}}};
function signup(user,write){return load('pages/api/signup-completion.js',{'../../lib/authServer':{getServerUser:async()=>user},'../../lib/supabaseServer':{createSupabaseServiceClient:()=>({})},'../../lib/funnelStore':{writeFunnelEvent:write},'../../lib/growthRules.cjs':require('../lib/growthRules.cjs')});}
test('confirmed signup has stable durable ID and frozen acquisition across retries',async()=>{const rows=[];const handler=signup(confirmed,async(_,row)=>{rows.push(row);return{error:null}});for(let i=0;i<2;i++){const res=response();await handler({method:'POST'},res);assert.equal(res.body.eligible,true);}assert.equal(rows[0].event_id,rows[1].event_id);assert.equal(rows[0].utm_campaign,'sports');assert(!rows[0].landing_page.includes('private@'));assert.equal(rows[0].event_at,confirmed.email_confirmed_at);});
test('unconfirmed and legacy users do not record completion',async()=>{for(const user of [{...confirmed,email_confirmed_at:null},{...confirmed,user_metadata:{}}]){const res=response();await signup(user,()=>assert.fail('unexpected write'))({method:'POST'},res);assert.equal(res.body.eligible,false);}});
test('unauthenticated signup endpoint rejects and storage errors stay failures',async()=>{let res=response();await signup(null,()=>{})({method:'POST'},res);assert.equal(res.code,401);res=response();await signup(confirmed,async()=>({error:{message:'down'}}))({method:'POST'},res);assert.equal(res.code,503);assert.equal(res.body.ok,false);});
test('public event endpoint cannot forge payment completion',async()=>{const handler=load('pages/api/events.js',{'../../lib/funnelStore':{writeFunnelEvent:()=>assert.fail('unexpected write')},'../../lib/supabaseServer':{hasSupabaseServiceConfig:()=>true},'../../lib/growthRules.cjs':require('../lib/growthRules.cjs')});for(const name of ['subscribe_success','checkout_success','signup_completed']){const res=response();await handler({method:'POST',body:{event_name:name}},res);assert.equal(res.code,400);}});
test('missing idempotency column fails rather than duplicating completions',async()=>{const store=loadStore();const out=await store({from:()=>({upsert:async()=>({error:{message:"Could not find the 'event_id' column"}})})},{event_id:'stable',event_name:'signup_completed'});assert(out.error);});
function loadStore(){const file='lib/funnelStore.js';const code=transformSync(fs.readFileSync(file,'utf8'),{filename:file,jsc:{parser:{syntax:'ecmascript'}},module:{type:'commonjs'}}).code;const module={exports:{}};vm.runInNewContext(code,{module,exports:module.exports});return module.exports.writeFunnelEvent;}

test('Stripe webhook and return verification share one paid completion ID',async()=>{
 const saved=new Map();const writes=[];const session={id:'cs_fixture',status:'complete',payment_status:'paid',created:1791385200,amount_total:4900,currency:'usd',metadata:{visitor_id:'visitor-fixture',session_id:'session-fixture',utm_source:'x',utm_campaign:'sports'}};
 class Stripe {constructor(){this.checkout={sessions:{retrieve:async()=>session}};this.webhooks={constructEvent:()=>({type:'checkout.session.completed',data:{object:session}})};}}
 const db={from:()=>({upsert:async()=>({error:null})})};const mock={'stripe':Stripe,'../../../lib/supabaseServer':{hasSupabaseServiceConfig:()=>true,createSupabaseServiceClient:()=>db},'../../../lib/growthRules.cjs':require('../lib/growthRules.cjs'),'../../../lib/funnelStore':{writeFunnelEvent:async(_,row)=>{writes.push(row);if(!saved.has(row.event_id))saved.set(row.event_id,row);return{error:null}}},'micro':{buffer:async()=>Buffer.from('fixture')}};
 const prior=process.env.STRIPE_SECRET_KEY;process.env.STRIPE_SECRET_KEY='sk_test_fixture';
 try{const verify=load('pages/api/stripe/verify-success.js',mock),webhook=load('pages/api/webhooks/stripe.js',mock);let res=response();await verify({method:'GET',query:{session_id:session.id}},res);assert.equal(res.code,200);assert.equal(res.body.purchase.value,49);res=response();await webhook({method:'POST',headers:{'stripe-signature':'fixture'}},res);assert.equal(res.code,200);assert.equal(saved.size,1);assert.equal(writes[0].event_id,writes[1].event_id);assert.equal(writes[0].utm_campaign,'sports');
 session.payment_status='unpaid';res=response();await verify({method:'GET',query:{session_id:session.id}},res);assert.equal(res.code,403);res=response();await webhook({method:'POST',headers:{'stripe-signature':'fixture'}},res);assert.equal(saved.size,1);assert.equal(writes.length,2);
 }finally{if(prior===undefined)delete process.env.STRIPE_SECRET_KEY;else process.env.STRIPE_SECRET_KEY=prior;}
});


test('GA initializes before the first event and strips sensitive URL fields',()=>{
 const window={location:{pathname:'/sports',href:'https://www.sharps-signal.com/sports?email=private@example.com&session_id=cs_secret&utm_source=x'}};const document={referrer:'https://x.com/?email=private@example.com'};const file='lib/ga.js',code=transformSync(fs.readFileSync(file,'utf8'),{filename:file,jsc:{parser:{syntax:'ecmascript'}},module:{type:'commonjs'}}).code;const module={exports:{}};vm.runInNewContext(code,{module,exports:module.exports,require:()=>require('../lib/growthRules.cjs'),process,window,document,Date});module.exports.gaEvent({action:'landing_view',parameters:{email:'private@example.com'}});const q=window.dataLayer;assert.equal(q[0][0],'js');assert.equal(q[1][0],'config');assert.equal(q[2][0],'event');assert(!JSON.stringify(q).includes('private@example.com'));assert(!JSON.stringify(q).includes('cs_secret'));module.exports.gaEvent({action:'signup_view'});assert.equal(q.length,4);
});
