import {useEffect,useState} from 'react';
import Link from 'next/link';
import {useRouter} from 'next/router';
import {supabase} from '../lib/supabaseClient';
import {getSafeNext,buildAuthCallbackUrl} from '../lib/authRedirect';
export default function Signin(){const router=useRouter();const [email,setEmail]=useState(''),[password,setPassword]=useState(''),[mode,setMode]=useState('password'),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');const next=getSafeNext(router.query.next);
useEffect(()=>{supabase.auth.getSession().then(({data})=>{if(data?.session)router.replace(next);});},[next]);
async function submit(e){e.preventDefault();setBusy(true);setError('');setMessage('');try{if(mode==='link'){const {error}=await supabase.auth.signInWithOtp({email:email.trim(),options:{shouldCreateUser:false,emailRedirectTo:buildAuthCallbackUrl(window.location.origin,next)}});if(error)throw error;setMessage('Check your inbox for a secure sign-in link. Open it in this browser to finish signing in.');}else{const {error}=await supabase.auth.signInWithPassword({email:email.trim(),password});if(error)throw error;await router.replace(next);}}catch(e){setError(e.message||'Unable to sign in. Please try again.');}finally{setBusy(false);}}
return <main className="auth-layout"><div className="auth-intro"><span className="eyebrow">WELCOME BACK</span><h1>Back to<br/><span>your signal.</span></h1><p>Your sports and market research, right where you left it.</p></div><section className="auth-card"><h2>Log in to SharpsSignal</h2><div className="segmented">{['password','link'].map(x=><button key={x} disabled={busy} aria-pressed={mode===x} onClick={()=>{setMode(x);setError('');setMessage('');}}>{x==='password'?'Password':'Email me a link'}</button>)}</div><form onSubmit={submit}><label htmlFor="email">Email</label><input id="email" type="email" autoComplete="email" required value={email} onChange={e=>setEmail(e.target.value)}/>{mode==='password'&&<><label htmlFor="password">Password</label><input id="password" type="password" autoComplete="current-password" required value={password} onChange={e=>setPassword(e.target.value)}/></>}{error&&<p role="alert" className="error-message">{error}</p>}{message&&<p role="status" className="success-message">{message}</p>}<button className="button-primary full-width" disabled={busy}>{busy?'Please wait…':mode==='password'?'Log in ↗':'Send secure sign-in link'}</button></form><div className="auth-links"><Link href="/reset-password">Forgot password?</Link><Link href="/signup">Create account</Link></div></section></main>}
