import {useState,useEffect} from 'react';
import Link from 'next/link';
import {useRouter} from 'next/router';
import {supabase} from '../lib/supabaseClient';
import {buildAuthCallbackUrl,getSafeNext} from '../lib/authRedirect';
import {getFirstTouch,getVisitorId,getSessionId,trackFunnelEvent} from '../lib/funnelClient';
export default function Signup(){const router=useRouter();const [email,setEmail]=useState(''),[password,setPassword]=useState(''),[show,setShow]=useState(false),[phone,setPhone]=useState(''),[interests,setInterests]=useState(['sports']),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState(''),[done,setDone]=useState(false);const requestedNext=getSafeNext(router.query.next,"/sports");const next=requestedNext==="/sports"&&!interests.includes("sports")?"/dashboard":requestedNext;
useEffect(()=>{supabase.auth.getSession().then(({data})=>{if(data?.session)router.replace(next);});},[next]);
async function submit(e){e.preventDefault();setBusy(true);setError('');try{if(!interests.length)throw Error('Choose Sports, Markets, or both.');let normalized=phone.trim().replace(/[\s().-]/g,'');if(normalized.startsWith('00'))normalized='+'+normalized.slice(2);else if(/^\d{10}$/.test(normalized))normalized='+1'+normalized;else if(/^1\d{10}$/.test(normalized))normalized='+'+normalized;if(normalized&&!/^\+[1-9]\d{7,14}$/.test(normalized))throw Error('Use a US number or include + and your country code.');const attribution=getFirstTouch();await trackFunnelEvent('signup_submit',{location:'member_signup'});const {data,error}=await supabase.auth.signUp({email:email.trim().toLowerCase(),password,options:{emailRedirectTo:buildAuthCallbackUrl(window.location.origin,next),data:{signup_tracking_version:2,signup_attribution:attribution,signup_visitor_id:getVisitorId(),signup_session_id:getSessionId(),interests,phone:normalized||null,phone_verified:false,utm_source:attribution.utm_source||null,utm_campaign:attribution.utm_campaign||null}}});if(error)throw error;if(data?.user?.identities?.length===0){setDone(true);setMessage('Check your email or log in if you already have an account.');return;}await trackFunnelEvent('account_created',{location:'member_signup',email_confirmation_required:!data?.session});if(data?.session){await fetch('/api/signup-completion',{method:'POST'});await router.replace(next);return;}await trackFunnelEvent('signup_confirmation_pending',{location:'member_signup'});setDone(true);setMessage('Check your email to confirm your account. The link will take you to your selected feed. If you already have an account, use Log in.');}catch(e){trackFunnelEvent('signup_error',{location:'member_signup'});setError(e.message||'Could not create your account. Please try again.');}finally{setBusy(false);}}
return <main className="auth-layout"><div className="auth-intro"><span className="eyebrow">YOUR SIGNAL STARTS HERE</span><h1>A little more<br/><span>clarity.</span></h1><p>Start with free sports research. Follow captured prices and recorded paper results; add Markets anytime.</p><div className="auth-note">Free account · Paper research · No card required</div></div><section className="auth-card"><h2>Create your account</h2><p className="muted">Create a free account, confirm your email, then explore Sports. No card required.</p>{done?<><div className="success-message" role="status">{message}</div><Link className="button-primary" href={`/signin?next=${encodeURIComponent(next)}`}>Log in after confirming</Link></>:<form onSubmit={submit}><label htmlFor="email">Email</label><input id="email" type="email" autoComplete="email" required value={email} onChange={e=>setEmail(e.target.value)}/><label htmlFor="password">Password <small>At least 8 characters</small></label><div className="password-field"><input id="password" type={show?'text':'password'} autoComplete="new-password" minLength={8} required value={password} onChange={e=>setPassword(e.target.value)}/><button type="button" aria-label={show?'Hide password':'Show password'} onClick={()=>setShow(!show)}>{show?'Hide':'Show'}</button></div><label htmlFor="phone">Phone <small>Optional · SMS is not active</small></label><input id="phone" type="tel" autoComplete="tel" placeholder="(212) 555-0123 or +44…" value={phone} onChange={e=>setPhone(e.target.value)}/><fieldset><legend>I’m interested in</legend><div className="interest-options">{['sports','markets'].map(x=><label key={x}><input type="checkbox" checked={interests.includes(x)} onChange={()=>setInterests(interests.includes(x)?interests.filter(i=>i!==x):[...interests,x])}/>{x==='sports'?'Sports':'Markets'}</label>)}</div></fieldset><p className="small muted">We store your contact details and interests for your account. Registering does not activate email, SMS, or push play alerts. <Link href="/privacy">Privacy</Link></p>{error&&<p role="alert" className="error-message">{error}</p>}<button className="button-primary full-width" disabled={busy}>{busy?'Creating account…':'Create account ↗'}</button></form>}<p className="small">Already have an account? <Link href={`/signin?next=${encodeURIComponent(next)}`}>Log in</Link></p></section></main>}
